### ISSUE TITLE
encoding/lib/cpu/enclib_cpu.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs

### ISSUE THREAD

**Issue by Ximoi** [nv-tlabs/GSCNN#11]
Hi, I met a package bug when trying to evaluate the method by 'python train.py --evaluate --snapshot checkpoints/best_cityscapes_checkpoint.pth'

The bug is :
Traceback (most recent call last):
  File "train.py", line 380, in <module>
    main()
  File "train.py", line 128, in main
    assert_and_infer_cfg(args)
  File "/home/fuyi02/vos/GSCNN/config.py", line 86, in assert_and_infer_cfg
    import encoding
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/lib/__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 971, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/fuyi02/anaconda3/envs/GSCNN/lib/python3.6/site-packages/encoding/lib/cpu/enclib_cpu.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs

It seems the unmatched packages in my conda env:
pytorch                   1.1.0
python                    3.6.9
torch-encoding       1.0.1
torchvision              0.2.0

So, is the torch encoding unmatched? Could you tell me how to fix it. Thank you!

**Comment by Ximoi** [comment]
Hi, I fix the bug by using pytorch==1.0.0 and torchvision==0.2.0.

**Comment by gaoyangxixi** [comment]
Hi,have you download the pretrained model?
I can not get it because i can not log in the google drive,please share with me,thank you.

**Comment by gaoyangxixi** [comment]
Hi,have you download the pretrained model?
I can not get it because i can not log in the google drive,please share with me,thank you.
my email is   gaox@dlmu.edu.cn

**Comment by renshasha** [comment]
I have the same problem with you, have you solved it?

**Comment by tovacinni** [comment]
https://github.com/nv-tlabs/GSCNN/pull/10

The dependencies listed in the Dockerfile here should work. Can you try it?

**Comment by Ximoi** [comment]
I will try it as soon as possible

**Comment by ayinaaaaaa** [comment]
> I will try it as soon as possible

hi,have you solved it?Do we need to use python3.5?thank you very much.

**Comment by mdt48** [comment]
Has anyone found the solution to this?

**Comment by ayinaaaaaa** [comment]
> Has anyone found the solution to this?

I also encountered this problem. It may be a problem with the pytorch version.When I changed pytorch to 1.1,cuda is 10.0，and torchvision is 0.3.0. the problem was solved.I hope it can help you

**Comment by mdt48** [comment]
@ayinaaaaaa Thank you for your help. Also, what did you have to change to train on your own data?

**Comment by ayinaaaaaa** [comment]
> @ayinaaaaaa Thank you for your help. Also, what did you have to change to train on your own data?

I just changed my dataset's name to cityscapes' format, and then changed numclasss = my category number. I only have background and annotation, so the  label  has 0 and 1. But the training results are very strange, they are all edges, I don't know why

**Comment by mdt48** [comment]
@ayinaaaaaa 

> > @ayinaaaaaa Thank you for your help. Also, what did you have to change to train on your own data?
> 
> I just changed my dataset's name to cityscapes' format, and then changed numclasss = my category number. I only have background and annotation, so the label has 0 and 1. But the training results are very strange, they are all edges, I don't know why

This is my first time doing such a thing and I have a couple more questions. By background do you mean the normal image? And where do you have this label?

**Comment by ayinaaaaaa** [comment]
> @ayinaaaaaa
> 
> > > @ayinaaaaaa Thank you for your help. Also, what did you have to change to train on your own data?
> > 
> > 
> > I just changed my dataset's name to cityscapes' format, and then changed numclasss = my category number. I only have background and annotation, so the label has 0 and 1. But the training results are very strange, they are all edges, I don't know why
> 
> This is my first time doing such a thing and I have a couple more questions. By background do you mean the normal image? And where do you have this label?

sorry，I don't quite understand what you mean. It's the first time I've done this. I don't know if it's right. The training can run well, but the result is a little strange. The mask of the Cityscapes dataset is the index image, so I convert the label into the index image. My label category only has one kind of label and background (for example, only people are labeled on a picture). After converting it into the index image, the index value of the background is 0. the index value of the label is 1. If you don't mind, can we communicate more easily, such QQ or wechat?Thank you !!

**Comment by mdt48** [comment]
> > @ayinaaaaaa
> > > > @ayinaaaaaa Thank you for your help. Also, what did you have to change to train on your own data?
> > > 
> > > 
> > > I just changed my dataset's name to cityscapes' format, and then changed numclasss = my category number. I only have background and annotation, so the label has 0 and 1. But the training results are very strange, they are all edges, I don't know why
> > 
> > 
> > This is my first time doing such a thing and I have a couple more questions. By background do you mean the normal image? And where do you have this label?
> 
> sorry，I don't quite understand what you mean. It's the first time I've done this. I don't know if it's right. The training can run well, but the result is a little strange. The mask of the Cityscapes dataset is the index image, so I convert the label into the index image. My label category only has one kind of label and background (for example, only people are labeled on a picture). After converting it into the index image, the index value of the background is 0. the index value of the label is 1. If you don't mind, can we communicate more easily, such QQ or wechat?Thank you !!


Unfortunately I do not. There is an image and its annotation for training that you give the algorithm, and all you have done is modify your dataset to fit the scheme of cityscapes. There is also only one class in each image? If thats the case I think i understand. Thank you for your speedy responses :)

**Comment by mdt48** [comment]
> > @ayinaaaaaa
> > > > @ayinaaaaaa Thank you for your help. Also, what did you have to change to train on your own data?
> > > 
> > > 
> > > I just changed my dataset's name to cityscapes' format, and then changed numclasss = my category number. I only have background and annotation, so the label has 0 and 1. But the training results are very strange, they are all edges, I don't know why
> > 
> > 
> > This is my first time doing such a thing and I have a couple more questions. By background do you mean the normal image? And where do you have this label?
> 
> sorry，I don't quite understand what you mean. It's the first time I've done this. I don't know if it's right. The training can run well, but the result is a little strange. The mask of the Cityscapes dataset is the index image, so I convert the label into the index image. My label category only has one kind of label and background (for example, only people are labeled on a picture). After converting it into the index image, the index value of the background is 0. the index value of the label is 1. If you don't mind, can we communicate more easily, such QQ or wechat?Thank you !!

How do you convert it into index image?

**Comment by ayinaaaaaa** [comment]
> How do you convert it into index image?

I only know how to convert the image of one label.There are programs to convert index images on the Internet. You can  refer to it.
