### ISSUE TITLE
collect_arguments(Args &&...args) {\n ^\n/usr/local/lib/python3.6/dist-packages/torch/include/pybind11/cast.h:2094:1: note:   template argument deduction/substitution failed:\nninja: build stopped: subcommand failed.\n'

### ISSUE THREAD

**Issue by XieZixiUSTC** [nv-tlabs/GSCNN#36]
i runned the command  python train.py --evaluate --snapshot checkpoints/best_cityscapes_checkpoint.pth after i changed the DIR name to /home/usrname/data/cityscapes , the mistakes with the pacages of  /python3.6/dist-packages/torch/include/pybind11/cast happened

**Comment by XieZixiUSTC** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 128, in main
    assert_and_infer_cfg(args)
  File "/home/xiezixi/GSCNN/config.py", line 86, in assert_and_infer_cfg
    import encoding
  File "/usr/local/lib/python3.6/dist-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/usr/local/lib/python3.6/dist-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/usr/local/lib/python3.6/dist-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/usr/local/lib/python3.6/dist-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/usr/local/lib/python3.6/dist-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/usr/local/lib/python3.6/dist-packages/encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 866, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
some people say is the problem of the pytorch version,,anyone econutered the same problem, apreciate to any reply,all thanks

**Comment by G-JH** [comment]
have you solved the problem about pybind11?

**Comment by lllyuubing** [comment]
hava you solved this problem?
