### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by shifangtian** [nv-tlabs/GSCNN#42]
Traceback (most recent call last):
  File "D:/my/torch-gpu/mu_yi_hua-GSCNN-master/GSCNN/train.py", line 381, in <module>
    main()
  File "D:/my/torch-gpu/mu_yi_hua-GSCNN-master/GSCNN/train.py", line 128, in main
    assert_and_infer_cfg(args)
  File "D:\my\torch-gpu\mu_yi_hua-GSCNN-master\GSCNN\config.py", line 86, in assert_and_infer_cfg
    import encoding
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .encoding import *
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\encoding\nn\encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .encoding import *
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\encoding\functions\encoding.py", line 14, in <module>
    from .. import lib
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\encoding\lib\__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 644, in load
    is_python_module)
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 862, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\utils\cpp_extension.py", line 1072, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by tovacinni** [comment]
Can you share your package versions and experimental setup?

**Comment by shifangtian** [comment]
cuda9.0
cudnn7.0
pytorch-gpu1.1.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Towaki"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 上午6:40
收件人:&nbsp;"nv-tlabs/GSCNN"<GSCNN@noreply.github.com&gt;;
抄送:&nbsp;"剑可入鞘否"<404716439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nv-tlabs/GSCNN] subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1. (#42)




Can you share your package versions and experimental setup?

**Comment by lqwfree** [comment]
Have you solved this problem?How to solve it?

**Comment by KL-Ding** [comment]
how to solve it？
