### ISSUE TITLE
 RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by DinghaoXi** [nv-tlabs/GSCNN#55]
12-19 13:34:32.121 evaluating: 67 / 500
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:10<00:00,  1.79it/s]
12-19 13:34:45.113 evaluating: 68 / 500
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.13it/s]
12-19 13:34:51.236 evaluating: 69 / 500
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:10<00:00,  1.74it/s]
12-19 13:35:04.922 evaluating: 70 / 500
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.54it/s]
Traceback (most recent call last):
  File "train.py", line 385, in <module>
    main()
  File "train.py", line 144, in main
    evaluate(val_loader, net)
  File "train.py", line 358, in evaluate
    for vi, data in enumerate(val_loader):
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/xidh/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

I don't know why its stopped...

**Comment by ashantia** [comment]
You are running out of RAM. I am having the same problem with 64GB of RAM. Exactly after the validation step, RAM usage goes up for each evaluation step. Mine goes up to 69. I will check how this can be avoided.
