### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by lqwfree** [nv-tlabs/GSCNN#66]
信息: 用提供的模式无法找到文件。
F:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:190: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
信息: 用提供的模式无法找到文件。
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/GSCNN-master/train.py", line 385, in <module>
    main()
  File "F:/GSCNN-master/train.py", line 132, in main
    assert_and_infer_cfg(args)
  File "F:\GSCNN-master\config.py", line 88, in assert_and_infer_cfg
    import encoding
  File "F:\Anaconda3\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "F:\Anaconda3\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .encoding import *
  File "F:\Anaconda3\lib\site-packages\encoding\nn\encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "F:\Anaconda3\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .encoding import *
  File "F:\Anaconda3\lib\site-packages\encoding\functions\encoding.py", line 14, in <module>
    from .. import lib
  File "F:\Anaconda3\lib\site-packages\encoding\lib\__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "F:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 661, in load
    is_python_module)
  File "F:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "F:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 879, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "F:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1159, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "F:\Anaconda3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "F:\Anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Process finished with exit code 1

Anyone solve this?Many thanks?

**Comment by KL-Ding** [comment]
I have the same problem

**Comment by oxygen39** [comment]
Have you solved the problem？

**Comment by June-Luo** [comment]
Hi,I also met the same problem.Have you solved it?

**Comment by Tristesse-stk** [comment]
本人直接将main()函数的第一行代码assert_and_infer_cfg(args)给注释掉，能跑起来
